version: '3.9'

services:
    photoric:
        build: . 
        #--file Dockerfile --tag photoric:$(date +%s)
        #volumes:
        #    - .:/photoric
        ports:
            - "8000:5000"
        depends_on: 
            - db
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: photoric
          POSTGRES_PASSWORD: ${DB_PASSWORD}
