version: '3.9'

services:
    photoric:
        container_name: photoric
        build:
          context: . 
        #--file Dockerfile --tag photoric:$(date +%s)
        #volumes:
        #    - .:/photoric
        ports:
            - "8000:5000"
        environment:
            SECRET_KEY: ${PHOTORIC_KEY}
            PHOTO_STORAGE: 'storage'
            DB_SERVER: 'photoric_db:5432'
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on: 
            - db
    db:
        container_name: photoric_db
        image: postgres
        restart: always
        environment:
          POSTGRES_DB: photoric
          POSTGRES_USER: photoric
          POSTGRES_PASSWORD: ${DB_PASSWORD}
