name: "Docker Compose CI"

on:
  repository_dispatch:
    types: [trigger-workflow-3]
  #workflow_run:
  #  workflows: [ Python package ]
  #  types: [ completed ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
        sha: ${{ github.event.client_payload.sha }}
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag photoric:$(date +%s)
    - name: Build the Docker stack
      run: docker-compose build --no-deps photoric
